export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";
export const GET_PROFILES = "GET_PROFILES";
export const POST_LOADING = "POST_LOADING";
export const GET_POSTS = "GET_POSTS";
export const GET_POST = "GET_POST";
export const ADD_POST = "ADD_POST";
export const DELETE_POST = "DELETE_POST";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const GET_CLIENT_MACROS = "GET_CLIENT_MACROS";
export const GET_CLIENT_LIST = "GET_CLIENT_LIST";
export const SET_CLIENT_MACROS = "SET_CLIENT_LIST";

export const PROGRESS_UPDATE_LOADING = "PROGRESS_UPDATE_LOADING";
export const GET_PROGRESS_UPDATES = "GET_PROGRESS_UPDATES";
export const GET_PROGRESS_UPDATE = "GET_PROGRESS_UPDATE";
export const ADD_PROGRESS_UPDATE = "ADD_PROGRESS_UPDATE";
export const GET_PROGRESS_PHOTOS = "GET_PROGRESS_PHOTOS";
export const DELETE_PROGRESS_UPDATE = "DELETE_PROGRESS_UPDATE";
export const SET_USER_AVATAR = "SET_USER_AVATAR";

